id: P21DCC9C3
initial_creation_type: input
source_metadata:
  title: Nirukta
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Vedāṅga -- Prātiśākhya
  data entry: Munoe Tokunaga (and partly M. Kobayashi)
  contribution to GRETIL: Munoe Tokunaga (and partly M. Kobayashi)
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:51:16.077337'
last_modified_at: '2022-03-09T14:51:16.077349'
